from . import DateTimeGenerator

def getImplementation(plannedStartTime, vendorTimeInImplementation, cisInImplementation):

    # 在Implementation Plan中的起始时间
    startTimeInImplementation = DateTimeGenerator.getStartTimeInImplementation(plannedStartTime)

    # 在Implementation Plan中的Vendor的维护时间
    declaration = "Vendor Start Date  Vendor End Date    Window\n" + vendorTimeInImplementation + "\n\n" + cisInImplementation + "\n\nStart this change 45 minutes in advance at " + startTimeInImplementation + "PT\n\n"

    # 生成Implementation Plan
    implementation = declaration + (
        'WAN/DDS/Transit/Private/LOCAL/Public Peering:\n'
        '\n'
        '  Cost-out procedure:\n'
        '\n'
        '    a. Follow current Think Twice/SEC procedures and get change to \"In Progress\"\n'
        '      i. Should be on the change bridge and announce the change going to \"Ready to Start\" in the Slack channel.\n'
        '\n'
        '    b. Login to preferred MTBB automation server\n'
        '\n'
        '    c. For WAN/DDS/Transit/Private/LOCAL: Run the following command:\n'
        '      i. WAN & DDS PRE-maintenance\n'
        '        1. maint_vendors.py -cid <cid>\n'
        '      ii. Transit & Private PRE-maintenance\n'
        '        1. maint_vendors.py -tp <cid>\n'
        '      iii. LOCAL & WAN & DDS PRE-maintenance\n'
        '        1. maint_vendors.py -dev <router> -int <interface>\n'
        '\n'
        '    d. For Public Peering: Run the following command:\n'
        '      i. This will gather all peers on the router with that ASN and generates the PRE-maintenance configs to apply the route filters\n'
        '        1. maint_vendors.py -pp -dev <router> -as <asn>\n'
        '      ii. This will cost out ALL peering sessions on that router through that interface by APPLYING  route filters to every neighbor\n'
        '        1. maint_vendors.py -pp -dev <router_name> -int <interface> -all\n'
        '      iii. This will gather all neighbors belonging to ASN on BOTH edge routers at the location (ber1 & ber2) and generate PRE-maintenance configs to APPLY route filters\n'
        '        1. maint_vendors.py -pp -dev <router> -as <asn>\n'
        '\n'
        '    e. Enter your TACACS+ password when prompted and enter\n'
        '\n'
        '    f. Monitor the output to make sure the following happen successfully\n'
        '      i.  Configuration push\n'
        '      ii. Tunnel reoptimization\n'
        '\n'
        '    g. Perform verification\n'
        '      i.   MAINT added to description\n'
        '      ii.  The admin-group maintenance should be applied under protocols mpls\n'
        '      iii. The metric should be set under protocols isis level 2 to 65000\n'
        '\n'
        '    h. Document verification in a Message Update (or equivalent in SNOW)\n'
        '\n'
        'After vendor maintenance has been completed, circuit should be ready to put back in service.\n'
        '\n'
        '  Cost-in procedure:\n'
        '\n'
        '    a. Login to preferred MTBB automation server\n'
        '\n'
        '    b. Verify circuit before putting back in service\n'
        '      i.   IS-IS neighbor Up\n'
        '      ii.  Ping with max mtu (IPv4 = 8972, IPv6 = 8952) successfully\n'
        '      iii. Check interfaces for errors.  Clear before testing if errors accumulated during the maintenance.\n'
        '\n'
        '    c. For WAN/DDS/Transit/Private/LOCAL: Run the following command:\n'
        '      i. WAN & DDS POST-maintenance\n'
        '        1. maint_vendors.py -post -cid <cid>\n'
        '      ii. Transit & Private POST-maintenance\n'
        '        1. maint_vendors.py -post -tp <cid>\n'
        '      iii. LOCAL & WAN & DDS POST-maintenance\n'
        '        1. maint_vendors.py -post -dev <router> -int <interface>\n'
        '\n'
        '    d. For Public Peering: Run the following command:\n'
        '      i. This will gather all peers on the router with that ASN and generates the POST-maintenance configs to apply the route filters\n'
        '        1. maint_vendors.py -post -pp -dev <router> -as <asn>\n'
        '      ii. This will cost in ALL peering sessions on that router through that interface by APPLYING  route filters to every neighbor\n'
        '        1. maint_vendors.py -post -pp -dev <router_name> -int <interface> -all\n'
        '      iii. This will gather all neighbors belonging to ASN on BOTH edge routers at the location (ber1 & ber2) and generate POST-maintenance configs to APPLY route filters\n'
        '        1. maint_vendors.py -post -pp -dev <router> -as <asn>\n'
        '\n'
        '    e. Enter your TACACS+ password when prompted and enter\n'
        '\n'
        '    f. Monitor the output to verify configuration push\n'
        '\n'
        '    g. Perform final verification\n'
        '      i.   MAINT removed from description\n'
        '      ii.  The admin-group maintenance should no longer be applied under protocols mpls\n'
        '        1. NOTE: if the admin-group maintenance is not in the output, that is exactly what is expected.\n'
        '      iii. The metric should be set back to the original value (matching the metric in the description)\n'
        '\n'
        '    h. Document final verification in a Message Update (or equivalent in SNOW)\n'
        '      i. Complete the change request and follow current Think Twice/SEC procedures to announce complete.\n'
        '\n'
        '    i. Generally should be announcing in Slack channel that CHNGE is complete unless there is an issue.\n'
        '\n'
        '\n'
        'Verification:\n'
        '\n'
        '  a. Verification of circuits is automatically ran utilizing the view_circuit_output.py script as part of the maint_vendors.py script. The view_circuit_output.py script is called directly after tunnel re-optimization has occurred during cost out and directly after the configurations have been pushed during post-maintenance.\n'
        '    i.  The output may take some time as the script will go to each device to gather the output. Some responses may take longer then others. For example, if the circuit is down, then ping may take additional time to complete.\n'
        '    ii. Copy all of the verification output into the associated tickets\n'
        '\n'
        'Move the status to Complete. Close code Complete as Planned\n'
        '\n'
        'External Email\n'
        '\n'
    )

    return implementation
